export const SETUP_FLAG = "SETUP_FLAG"

export const FETCH_USER = "FETCH_USER"

export const CHANGE_USER = "CHANGE_USER"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"